# Generated by Django 2.1 on 2019-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(default='暂无', max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
