# Generated by Django 2.1 on 2019-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='qq',
            field=models.CharField(default='暂无', max_length=20, unique=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wx',
            field=models.CharField(default='暂无', max_length=20, unique=True, verbose_name='微信'),
        ),
    ]
