# Generated by Django 2.1 on 2019-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190530_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='qq',
            field=models.CharField(max_length=20, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='wx',
            field=models.CharField(max_length=20, unique=True, verbose_name='微信'),
        ),
    ]
